# Generated by Django 5.2 on 2025-04-10 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimateApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('unit', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('estimate_title', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('workmanship', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_materials', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='estimateApp.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='EstimateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=2, max_digits=10)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='estimateApp.estimate')),
                ('chosen_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estimateApp.materialdescription')),
            ],
        ),
    ]
