# Generated by Django 5.2 on 2025-04-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimateApp', '0002_materialdescription_estimate_estimateitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialdescription',
            name='unit',
        ),
        migrations.AddField(
            model_name='estimateitem',
            name='unit',
            field=models.CharField(choices=[('pieces', 'Pieces'), ('meters', 'Meters'), ('yards', 'Yards'), ('feet', 'Feet'), ('coils', 'Coils'), ('kg', 'Kilograms'), ('units', 'Units')], default='pieces', max_length=20),
        ),
    ]
