# Generated by Django 5.2 on 2025-04-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimateApp', '0003_remove_materialdescription_unit_estimateitem_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimateitem',
            name='unit',
            field=models.CharField(choices=[('pieces', 'Pieces'), ('meters', 'Meters'), ('yards', 'Yards'), ('feet', 'Feet'), ('coils', 'Coils'), ('kg', 'Kilograms'), ('boxes', 'Boxes'), ('units', 'Units'), ('liters', 'Liters'), ('gallons', 'Gallons'), ('Spools', 'spools'), ('rolls', 'Rolls'), ('pairs', 'Pairs'), ('sets', 'Sets'), ('Packs', 'packs'), ('cartons', 'Cartons'), ('Dozens', 'dozens'), ('bundles', 'Bundles'), ('Palettes', 'palettes'), ('reels', 'Reels'), ('Crates', 'crates'), ('Tubes', 'tubes'), ('bags', 'Bags'), ('Cans', 'cans'), ('Bars', 'bars'), ('sacks', 'Sacks'), ('Squares', 'squares'), ('sheets', 'Sheets'), ('Drum', 'drum'), ('Cases', 'cases'), ('bottles', 'Bottles'), ('Jars', 'jars'), ('trays', 'Trays'), ('Tanks', 'tanks'), ('Strips', 'strips'), ('plates', 'Plates'), ('blocks', 'Blocks'), ('Cubes', 'cubes'), ('Canisters', 'canisters')], default='pieces', max_length=20),
        ),
    ]
